# Introduction to Numpy

**NumPy 库在科学计算生态圈中具有重要和基础的地位**

- extension package to Python for multi-dimensional arrays
- closer to hardware (efficiency, basic on *c*)
- designed for scientific computation (convenience)
- array oriented computing (张量计算)

**Python objects**

- high-level number objects: integers, floating point
- containers: lists (costless insertion and append), dictionaries (fast lookup). Memory-efficient container that provides fast numerical operations.
- NumPy is a linear algebra library for python
- Basic building blocks for almost all of the libraries in the PyData Ecosystem
- Numpy is also incredibly fast, as it has binding to C libraries.
- Numpy arrays: vectors and matrices
- Broadcasting: simplified, but powerful array interactions

**NumPy 是使用 Python 进行科学计算的基础软件包**
- 功能强大的N维数组对象。
- 精密广播功能函数。
- 集成 C/C+和Fortran 代码的工具。
- 强大的线性代数、傅立叶变换和随机数功能。

**支持 NumPy 的线性代数库**

- Default BLAS & Lapack
- [OpenBLAS](https://www.openblas.net/)
- [Intel MKL](https://software.intel.com/en-us/mkl): 对于 Intel CPU 这是最快的。
- [ATLAS](http://math-atlas.sourceforge.net/)

**参考资料**
- [中文官网](https://www.numpy.org.cn/)

# NumPy Arrays vs List

## List in Python

In [3]:
my_list = [1,2,3]

In [4]:
my_list

[1, 2, 3]

In [5]:
my_list + [2,3]

[1, 2, 3, 2, 3]

In [6]:
my_list.append(3)
print(my_list)

[1, 2, 3, 3]


## Array in NumPy

`NumPy` 最重要的一个特点是其 N 维数组对象 `ndarray`，它是一系列同类型数据的集合，以 0 下标为开始进行集合中元素的索引。`ndarray` 对象是用于存放同类型元素的多维数组。`ndarray` 中的每个元素在内存中都有相同存储大小的区域。

### 定义 np.array 的方法

- `np.array()` : 将 list 化成 array
- `np.arange()`
- `np.linspace()`
- `np.zeros`, `np.ones`, `np.eye`
- `np.random.rand`, `np.random.randn`, `np.random.randint`


In [1]:
import numpy as np

In [7]:
arr = np.array(my_list)

In [9]:
arr + [2,3]

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [10]:
my_array = np.array([11,12,13])
print(my_array.shape)

(3,)


In [11]:
my_array2 = np.array([[11,12,13]])
my_array2.shape

(1, 3)

In [13]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [14]:
print(np.array(my_mat).shape)

(3, 3)


In [15]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(0,11,1.5)

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5])

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.random.rand(3,3)

array([[0.35751765, 0.42156678, 0.49451594],
       [0.23077607, 0.82886597, 0.09945415],
       [0.94168969, 0.77592567, 0.96992981]])

In [27]:
np.random.randn(3,3)

array([[-1.08524156, -0.7241752 ,  1.68893035],
       [-0.90033409,  0.16852281, -1.05131763],
       [-0.6030041 ,  1.02820941, -1.52375809]])

In [28]:
np.random.randint(1,100,10) # 10 个 1 到 100 间的随机整数

array([44, 42, 77, 43, 32, 56, 42,  7, 67, 91])

In [105]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [106]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [107]:
arr.max()

8

In [32]:
arr.min()

0

In [33]:
arr.argmin() # 返回最小值的 index

0

In [34]:
arr.argmax() # 返回最大值的 index

8

In [35]:
arr.shape

(9,)

In [36]:
arr.dtype

dtype('int32')

In [37]:
my_array.dtype

dtype('int32')

In [38]:
arr = np.array([1,2,3],dtype=np.float64)
arr

array([1., 2., 3.])

## 索引(Indexing)和切片(Slicing)

In [39]:
arr = np.arange(0,11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[8]

8

In [42]:
arr[-1]

10

In [43]:
arr[1:5]

array([1, 2, 3, 4])

In [44]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [46]:
arr[:] = 100

In [47]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [48]:
arr = np.arange(0,11)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
slice_of_arr = arr[0:6]

In [51]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [52]:
slice_of_arr[:]=99

In [53]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [54]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [55]:
arr_copy=arr.copy()

In [56]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [57]:
arr_copy[:]=100

In [58]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [59]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [60]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [61]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [62]:
arr_2d[0][0]

5

In [63]:
arr_2d[0]

array([ 5, 10, 15])

In [64]:
arr_2d[1][1]

25

In [65]:
arr_2d[1,1]

25

## Numpy operations

* Array with array
* Array with Scalars (broadcasting)
* universal array functions

In [66]:
arr = np.arange(0,11)

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr - 5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [69]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [70]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [71]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [72]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [73]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [74]:
arr.max()

10

In [75]:
np.max(arr)

10

In [76]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [78]:
arr1 = np.random.randn(5,1)

In [79]:
arr1.shape

(5, 1)

In [80]:
arr1 + 100

array([[ 98.1609876 ],
       [ 98.44360934],
       [ 99.76566112],
       [ 99.97466665],
       [100.25427944]])

In [81]:
arr2 = arr1.T

In [82]:
arr2

array([[-1.8390124 , -1.55639066, -0.23433888, -0.02533335,  0.25427944]])

In [83]:
arr2 + 100

array([[ 98.1609876 ,  98.44360934,  99.76566112,  99.97466665,
        100.25427944]])

In [84]:
arr3 = np.random.randn(5,3)

In [85]:
arr3

array([[-0.25908414, -0.16479051,  1.19897035],
       [ 1.11498787,  0.72136162, -2.31203202],
       [ 1.32973848, -0.46110732, -1.48747672],
       [ 1.25974269, -0.51248962,  0.29044201],
       [-0.63221798,  0.56082041,  1.22484618]])

In [86]:
arr3 + arr1

array([[-2.09809654, -2.00380291, -0.64004205],
       [-0.44140279, -0.83502904, -3.86842268],
       [ 1.0953996 , -0.6954462 , -1.7218156 ],
       [ 1.23440934, -0.53782297,  0.26510866],
       [-0.37793855,  0.81509985,  1.47912561]])

# 条件过滤



In [87]:
import numpy as np
L = np.array([[12,22,32,56],[11,13,17,12]])

In [88]:
L

array([[12, 22, 32, 56],
       [11, 13, 17, 12]])

In [89]:
filter = (L >20)

In [90]:
filter

array([[False,  True,  True,  True],
       [False, False, False, False]])

In [91]:
L[filter]

array([22, 32, 56])

In [92]:
L[L>20]

array([22, 32, 56])

In [95]:
L

array([[ 12, 122, 132, 156],
       [ 11,  13,  17,  12]])

In [96]:
L [L>20] += 100
print(L)

[[ 12 222 232 256]
 [ 11  13  17  12]]


In [97]:
L[L % 2 == 0] += 100

In [98]:
L

array([[112, 322, 332, 356],
       [ 11,  13,  17, 112]])